CREATE TABLE contacts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP,
    email TEXT NOT NULL,
    content TEXT NOT NULL,
    responded INTEGER NOT NULL
);